### ISSUE TITLE
Suggest to keep all static value that meant for configuration in to one specific file

### ISSUE THREAD

**Issue by chunyit** [yyyyyxuan/SuitCase_FINAL#3]
https://github.com/yyyyyxuan/SuitCase_FINAL/blob/3850ba15cdefe240101d6d46919f5430719c4ef0/Program.cs#L47
https://github.com/yyyyyxuan/SuitCase_FINAL/blob/3850ba15cdefe240101d6d46919f5430719c4ef0/Program.cs#L64
https://github.com/yyyyyxuan/SuitCase_FINAL/blob/3850ba15cdefe240101d6d46919f5430719c4ef0/Program.cs#L79
https://github.com/yyyyyxuan/SuitCase_FINAL/blob/3850ba15cdefe240101d6d46919f5430719c4ef0/Program.cs#L102

**Comment by yyyyyxuan** [comment]
added config file
